In [1]:
import pandas as pd

In [2]:
acq = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\acquisition.csv")
app = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\applications.csv")
collections = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\collections.csv")
credit_risk = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\credit_risk_history.csv")
customers = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\customers.csv")
loans = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\loans.csv")
monthly_kpis = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\monthly_business_kpis.csv")
repayments = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Learning Materials\Projects\Unguided project\finance project\dataset\repayments.csv")

## Checking customers and credit risk tables to see customer profile

In [3]:
customers.head(5)

,customer_id,registration_date,age,gender,nationality_group,city,employment_status,employment_sector,employment_tenure_months,monthly_income,housing_status,dependents,customer_tenure_months,acquisition_channel,acquisition_campaign,customer_segment
0,C100000,2024-03-06,21,Male,Saudi,Riyadh,Contract,Other,78,4500,Rented,1,21,Direct,Direct_Web,Low Income
1,C100001,2025-07-19,32,Male,Saudi,Riyadh,Salaried,Government,21,16500,Family,3,5,Social Media,Social_Prospecting,Upper-Middle Income
2,C100002,2025-04-23,21,Female,Saudi,Riyadh,Salaried,SME,76,7900,Rented,1,8,Social Media,Social_Retargeting,Middle Income
3,C100003,2024-11-16,54,Male,Other,Riyadh,Salaried,Private,39,11700,Rented,2,13,Paid Search,Search_Brand,Upper-Middle Income
4,C100004,2024-11-12,38,Male,Saudi,Riyadh,Unemployed,Private,73,7800,Owned,6,13,Organic,SEO_Organic,Middle Income

In [4]:
customers = customers.drop(['acquisition_channel','acquisition_campaign'], axis = 1)

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               40000 non-null  str
 1   registration_date         40000 non-null  str
 2   age                       40000 non-null  int64
 3   gender                    40000 non-null  str
 4   nationality_group         40000 non-null  str
 5   city                      40000 non-null  str
 6   employment_status         40000 non-null  str
 7   employment_sector         40000 non-null  str
 8   employment_tenure_months  40000 non-null  int64
 9   monthly_income            40000 non-null  int64
 10  housing_status            40000 non-null  str
 11  dependents                40000 non-null  int64
 12  customer_tenure_months    40000 non-null  int64
 13  customer_segment          40000 non-null  str
dtypes: int64(5), str(9)
memory usage: 4.3 MB

In [6]:
customers['registration_date']= pd.to_datetime(customers['registration_date'])

In [7]:
customers['gender'].value_counts()

gender
Male      27273
Female    12727
Name: count, dtype: int64

In [8]:
customers.columns

Index(['customer_id', 'registration_date', 'age', 'gender',
       'nationality_group', 'city', 'employment_status', 'employment_sector',
       'employment_tenure_months', 'monthly_income', 'housing_status',
       'dependents', 'customer_tenure_months', 'customer_segment'],
      dtype='str')

In [9]:
cols = ['gender','nationality_group','employment_status', 'employment_sector',
       'housing_status','customer_segment']

for col in cols:
    print(customers[col].unique())
    print('=='*50)

<StringArray>
['Male', 'Female']
Length: 2, dtype: str
====================================================================================================
<StringArray>
['Saudi', 'Other', 'GCC']
Length: 3, dtype: str
====================================================================================================
<StringArray>
['Contract', 'Salaried', 'Unemployed', 'Self-employed']
Length: 4, dtype: str
====================================================================================================
<StringArray>
['Other', 'Government', 'SME', 'Private', 'Freelance']
Length: 5, dtype: str
====================================================================================================
<StringArray>
['Rented', 'Family', 'Owned', 'Other']
Length: 4, dtype: str
====================================================================================================
<StringArray>
['Low Income', 'Upper-Middle Income', 'Middle Income', 'High Income']
Length: 4, dtype: str
====================================================================================================

In [10]:
customers.duplicated().sum()

np.int64(0)

In [11]:
customers.groupby('customer_id')['customer_id'].count()

customer_id
C100000    1
C100001    1
C100002    1
C100003    1
C100004    1
          ..
C139995    1
C139996    1
C139997    1
C139998    1
C139999    1
Name: customer_id, Length: 40000, dtype: int64

In [12]:
credit_risk.head()

,risk_assessment_id,customer_id,loan_id,assessment_date,credit_score,risk_score,risk_band,dti,loan_to_income,previous_late_payments,previous_defaults,probability_of_default
0,RA3000000,C118372,L2000000,2025-01-27,605,86,Low,0.0395,0.597,1,0,0.0229
1,RA3000001,C129120,L2000001,2025-08-14,715,97,Low,0.0300,1.037,0,0,0.0050
2,RA3000002,C112038,L2000002,2025-07-06,649,62,Medium,0.0300,0.652,2,0,0.0382
3,RA3000003,C101312,L2000003,2025-11-19,718,84,Low,0.0956,0.763,0,0,0.0753
4,RA3000004,C113241,L2000004,2025-08-20,717,89,Low,0.0387,1.266,0,0,0.0774

In [13]:
credit_risk = credit_risk.rename(columns = {'dti':'debt_to_income'})
credit_risk.head(5)

,risk_assessment_id,customer_id,loan_id,assessment_date,credit_score,risk_score,risk_band,debt_to_income,loan_to_income,previous_late_payments,previous_defaults,probability_of_default
0,RA3000000,C118372,L2000000,2025-01-27,605,86,Low,0.0395,0.597,1,0,0.0229
1,RA3000001,C129120,L2000001,2025-08-14,715,97,Low,0.0300,1.037,0,0,0.0050
2,RA3000002,C112038,L2000002,2025-07-06,649,62,Medium,0.0300,0.652,2,0,0.0382
3,RA3000003,C101312,L2000003,2025-11-19,718,84,Low,0.0956,0.763,0,0,0.0753
4,RA3000004,C113241,L2000004,2025-08-20,717,89,Low,0.0387,1.266,0,0,0.0774

In [14]:
credit_risk.info()

<class 'pandas.DataFrame'>
RangeIndex: 77030 entries, 0 to 77029
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   risk_assessment_id      77030 non-null  str
 1   customer_id             77030 non-null  str
 2   loan_id                 77030 non-null  str
 3   assessment_date         77030 non-null  str
 4   credit_score            77030 non-null  int64
 5   risk_score              77030 non-null  int64
 6   risk_band               77030 non-null  str
 7   debt_to_income          76646 non-null  float64
 8   loan_to_income          77030 non-null  float64
 9   previous_late_payments  77030 non-null  int64
 10  previous_defaults       77030 non-null  int64
 11  probability_of_default  77030 non-null  float64
dtypes: float64(3), int64(4), str(5)
memory usage: 7.1 MB

In [15]:
credit_risk['assessment_date']=pd.to_datetime(credit_risk['assessment_date'])

In [16]:
credit_risk['previous_defaults'].value_counts()

previous_defaults
0    76932
1       98
Name: count, dtype: int64

In [17]:
credit_risk['customer_id'].value_counts()

customer_id
C130109    13
C128959     9
C109434     9
C121195     9
C106243     9
           ..
C128268     1
C118453     1
C105876     1
C132686     1
C125024     1
Name: count, Length: 34101, dtype: int64

In [18]:
credit_risk[credit_risk['customer_id']=='C130109'].head()

,risk_assessment_id,customer_id,loan_id,assessment_date,credit_score,risk_score,risk_band,debt_to_income,loan_to_income,previous_late_payments,previous_defaults,probability_of_default
216,RA3000216,C130109,L2000216,2025-10-09,733,98,Low,0.0941,1.071,0,0,0.0466
1622,RA3001622,C130109,L2001622,2025-09-23,778,94,Low,0.0782,1.034,0,0,0.0450
10558,RA3010558,C130109,L2010558,2025-10-26,760,75,Low,0.0549,1.071,1,0,0.0624
14508,RA3014508,C130109,L2014508,2025-09-23,672,71,Medium,0.1282,1.071,0,0,0.0485
22088,RA3022088,C130109,L2022088,2025-10-01,657,82,Low,0.1177,1.429,0,0,0.0550

In [19]:
credit_risk['loan_id'].nunique()

77030

In [20]:
credit_risk.duplicated().sum()

np.int64(0)

In [21]:
(credit_risk.groupby('risk_assessment_id')['customer_id'].count() != 1).sum()

np.int64(0)

In [22]:
credit_risk.isna().sum()

risk_assessment_id          0
customer_id                 0
loan_id                     0
assessment_date             0
credit_score                0
risk_score                  0
risk_band                   0
debt_to_income            384
loan_to_income              0
previous_late_payments      0
previous_defaults           0
probability_of_default      0
dtype: int64

In [23]:
credit_risk[credit_risk['debt_to_income'].isna()].head(5)

,risk_assessment_id,customer_id,loan_id,assessment_date,credit_score,risk_score,risk_band,debt_to_income,loan_to_income,previous_late_payments,previous_defaults,probability_of_default
27,RA3000027,C128358,L2000027,2025-08-28,736,93,Low,NaN,1.111,0,0,0.0050
312,RA3000312,C125792,L2000312,2024-12-04,597,62,Medium,NaN,0.290,1,0,0.0389
469,RA3000469,C119101,L2000469,2025-12-15,776,95,Low,NaN,1.167,0,0,0.0050
724,RA3000724,C126602,L2000724,2024-12-08,590,67,Medium,NaN,1.314,3,0,0.1472
866,RA3000866,C139069,L2000866,2025-12-02,787,92,Low,NaN,0.843,0,0,0.1051

In [24]:
credit_risk['risk_band'].unique()

<StringArray>
['Low', 'Medium', 'High', 'Very High']
Length: 4, dtype: str

## Checking loans and applications tables

In [25]:
loans.head()

,loan_id,application_id,customer_id,disbursement_date,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,risk_band,acquisition_channel,underwriting_policy_version,maturity_date,loan_status
0,L2000000,APP1000001,C118372,2025-01-27,4000,12,0.1090,353.34,Personal,Low,Referral,Policy_V1,2026-01-22,Defaulted
1,L2000001,APP1000003,C129120,2025-08-14,8500,24,0.0920,389.10,Personal,Low,Organic,Policy_V2,2027-08-04,Active
2,L2000002,APP1000004,C112038,2025-07-07,7500,36,0.1052,243.84,Personal,Medium,Direct,Policy_V2,2028-06-21,Active
3,L2000003,APP1000006,C101312,2025-11-20,9000,12,0.0914,787.65,Personal,Low,Affiliate,Policy_V2,2026-11-15,Paid
4,L2000004,APP1000007,C113241,2025-08-21,10000,24,0.0916,457.58,Consumer,Low,Affiliate,Policy_V2,2027-08-11,Paid

In [26]:
loans.info()

<class 'pandas.DataFrame'>
RangeIndex: 77030 entries, 0 to 77029
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_id                      77030 non-null  str
 1   application_id               77030 non-null  str
 2   customer_id                  77030 non-null  str
 3   disbursement_date            77030 non-null  str
 4   approved_amount              77030 non-null  int64
 5   loan_term_months             77030 non-null  int64
 6   annual_rate                  77030 non-null  float64
 7   monthly_payment              77030 non-null  float64
 8   loan_type                    77030 non-null  str
 9   risk_band                    77030 non-null  str
 10  acquisition_channel          77030 non-null  str
 11  underwriting_policy_version  77030 non-null  str
 12  maturity_date                77030 non-null  str
 13  loan_status                  77030 non-null  str
dtypes: float64(2), int64(2), str(10)
memory usage: 8.2 MB

In [27]:
loans['disbursement_date'] = pd.to_datetime(loans['disbursement_date'])
loans['maturity_date'] = pd.to_datetime(loans['maturity_date'])

In [28]:
loans.duplicated().value_counts()

False    77030
Name: count, dtype: int64

In [29]:
loans['loan_id'].nunique()

77030

In [30]:
loans.columns

Index(['loan_id', 'application_id', 'customer_id', 'disbursement_date',
       'approved_amount', 'loan_term_months', 'annual_rate', 'monthly_payment',
       'loan_type', 'risk_band', 'acquisition_channel',
       'underwriting_policy_version', 'maturity_date', 'loan_status'],
      dtype='str')

In [31]:
cols = ['loan_type', 'risk_band', 'acquisition_channel',
       'underwriting_policy_version', 'loan_status']

for col in cols:
    print(f' Unique values in column {col}: {loans[col].unique()}')
    print('='*50)

 Unique values in column loan_type: <StringArray>
['Personal', 'Consumer', 'Education', 'Emergency']
Length: 4, dtype: str
==================================================
 Unique values in column risk_band: <StringArray>
['Low', 'Medium', 'High', 'Very High']
Length: 4, dtype: str
==================================================
 Unique values in column acquisition_channel: <StringArray>
[    'Referral',      'Organic',       'Direct',    'Affiliate',
  'Paid Search', 'Social Media',        'Email',      'Partner']
Length: 8, dtype: str
==================================================
 Unique values in column underwriting_policy_version: <StringArray>
['Policy_V1', 'Policy_V2']
Length: 2, dtype: str
==================================================
 Unique values in column loan_status: <StringArray>
['Defaulted', 'Active', 'Paid', 'Restructured', 'Written Off']
Length: 5, dtype: str
==================================================

In [32]:
# Checking if risk band col in credit risk and loans table are exactly same
temp = pd.merge(credit_risk,loans,how = 'inner',on = credit_risk['loan_id'])
temp.head()

,key_0,risk_assessment_id,customer_id_x,loan_id_x,assessment_date,credit_score,risk_score,risk_band_x,debt_to_income,loan_to_income,...,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,risk_band_y,acquisition_channel,underwriting_policy_version,maturity_date,loan_status
0,L2000000,RA3000000,C118372,L2000000,2025-01-27,605,86,Low,0.0395,0.597,...,4000,12,0.1090,353.34,Personal,Low,Referral,Policy_V1,2026-01-22,Defaulted
1,L2000001,RA3000001,C129120,L2000001,2025-08-14,715,97,Low,0.0300,1.037,...,8500,24,0.0920,389.10,Personal,Low,Organic,Policy_V2,2027-08-04,Active
2,L2000002,RA3000002,C112038,L2000002,2025-07-06,649,62,Medium,0.0300,0.652,...,7500,36,0.1052,243.84,Personal,Medium,Direct,Policy_V2,2028-06-21,Active
3,L2000003,RA3000003,C101312,L2000003,2025-11-19,718,84,Low,0.0956,0.763,...,9000,12,0.0914,787.65,Personal,Low,Affiliate,Policy_V2,2026-11-15,Paid
4,L2000004,RA3000004,C113241,L2000004,2025-08-20,717,89,Low,0.0387,1.266,...,10000,24,0.0916,457.58,Consumer,Low,Affiliate,Policy_V2,2027-08-11,Paid

In [33]:
temp[temp['risk_band_x'] != temp['risk_band_y']]

Empty DataFrame
Columns: [key_0, risk_assessment_id, customer_id_x, loan_id_x, assessment_date, credit_score, risk_score, risk_band_x, debt_to_income, loan_to_income, previous_late_payments, previous_defaults, probability_of_default, loan_id_y, application_id, customer_id_y, disbursement_date, approved_amount, loan_term_months, annual_rate, monthly_payment, loan_type, risk_band_y, acquisition_channel, underwriting_policy_version, maturity_date, loan_status]
Index: []

[0 rows x 27 columns]

In [34]:
loans = loans.drop(['risk_band'],axis =1)
loans.head()

,loan_id,application_id,customer_id,disbursement_date,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,acquisition_channel,underwriting_policy_version,maturity_date,loan_status
0,L2000000,APP1000001,C118372,2025-01-27,4000,12,0.1090,353.34,Personal,Referral,Policy_V1,2026-01-22,Defaulted
1,L2000001,APP1000003,C129120,2025-08-14,8500,24,0.0920,389.10,Personal,Organic,Policy_V2,2027-08-04,Active
2,L2000002,APP1000004,C112038,2025-07-07,7500,36,0.1052,243.84,Personal,Direct,Policy_V2,2028-06-21,Active
3,L2000003,APP1000006,C101312,2025-11-20,9000,12,0.0914,787.65,Personal,Affiliate,Policy_V2,2026-11-15,Paid
4,L2000004,APP1000007,C113241,2025-08-21,10000,24,0.0916,457.58,Consumer,Affiliate,Policy_V2,2027-08-11,Paid

In [35]:
loans.head()

,loan_id,application_id,customer_id,disbursement_date,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,acquisition_channel,underwriting_policy_version,maturity_date,loan_status
0,L2000000,APP1000001,C118372,2025-01-27,4000,12,0.1090,353.34,Personal,Referral,Policy_V1,2026-01-22,Defaulted
1,L2000001,APP1000003,C129120,2025-08-14,8500,24,0.0920,389.10,Personal,Organic,Policy_V2,2027-08-04,Active
2,L2000002,APP1000004,C112038,2025-07-07,7500,36,0.1052,243.84,Personal,Direct,Policy_V2,2028-06-21,Active
3,L2000003,APP1000006,C101312,2025-11-20,9000,12,0.0914,787.65,Personal,Affiliate,Policy_V2,2026-11-15,Paid
4,L2000004,APP1000007,C113241,2025-08-21,10000,24,0.0916,457.58,Consumer,Affiliate,Policy_V2,2027-08-11,Paid

In [36]:
app.head()

,application_id,customer_id,application_date,requested_amount,requested_term_months,application_channel,acquisition_channel,credit_score,monthly_income_at_application,existing_debt,dti,previous_late_payments,previous_defaults,risk_score,risk_band,application_status,rejection_reason,underwriting_policy_version
0,APP1000000,C110393,2024-12-03,7000.0,12,Affiliate,Affiliate,592,9700,17055,0.1525,3,0,48,High,Rejected,Policy Criteria,Policy_V1
1,APP1000001,C118372,2025-01-25,4500.0,12,Referral,Referral,605,6700,2727,0.0395,1,0,86,Low,Approved,NaN,Policy_V1
2,APP1000002,C103907,2025-12-23,3000.0,12,Social Media,Social Media,575,1900,1612,0.0839,1,0,37,Very High,Rejected,High DTI,Policy_V2
3,APP1000003,C129120,2025-08-13,8500.0,24,Organic,Organic,715,8200,0,0.0300,0,0,97,Low,Approved,NaN,Policy_V2
4,APP1000004,C112038,2025-07-02,8500.0,36,Direct,Direct,649,11500,2145,0.0300,2,0,62,Medium,Approved,NaN,Policy_V2

In [37]:
app.info()

<class 'pandas.DataFrame'>
RangeIndex: 120250 entries, 0 to 120249
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   application_id                 120250 non-null  str
 1   customer_id                    120250 non-null  str
 2   application_date               120250 non-null  str
 3   requested_amount               120250 non-null  float64
 4   requested_term_months          120250 non-null  int64
 5   application_channel            120250 non-null  str
 6   acquisition_channel            120250 non-null  str
 7   credit_score                   120250 non-null  int64
 8   monthly_income_at_application  120250 non-null  int64
 9   existing_debt                  120250 non-null  int64
 10  dti                            119649 non-null  float64
 11  previous_late_payments         120250 non-null  int64
 12  previous_defaults              120250 non-null  int64
 13  risk_score                     120250 non-null  int64
 14  risk_band                      120250 non-null  str
 15  application_status             120250 non-null  str
 16  rejection_reason               37978 non-null   str
 17  underwriting_policy_version    120250 non-null  str
dtypes: float64(2), int64(7), str(9)
memory usage: 16.5 MB

In [38]:
app[app['application_channel']!=app['acquisition_channel']]

Empty DataFrame
Columns: [application_id, customer_id, application_date, requested_amount, requested_term_months, application_channel, acquisition_channel, credit_score, monthly_income_at_application, existing_debt, dti, previous_late_payments, previous_defaults, risk_score, risk_band, application_status, rejection_reason, underwriting_policy_version]
Index: []

In [39]:
#dropping one of the column as they are exactly same
app = app.drop(['acquisition_channel'],axis =1)

In [40]:
app['application_date'] = pd.to_datetime(app['application_date'])
app.head()

,application_id,customer_id,application_date,requested_amount,requested_term_months,application_channel,credit_score,monthly_income_at_application,existing_debt,dti,previous_late_payments,previous_defaults,risk_score,risk_band,application_status,rejection_reason,underwriting_policy_version
0,APP1000000,C110393,2024-12-03,7000.0,12,Affiliate,592,9700,17055,0.1525,3,0,48,High,Rejected,Policy Criteria,Policy_V1
1,APP1000001,C118372,2025-01-25,4500.0,12,Referral,605,6700,2727,0.0395,1,0,86,Low,Approved,NaN,Policy_V1
2,APP1000002,C103907,2025-12-23,3000.0,12,Social Media,575,1900,1612,0.0839,1,0,37,Very High,Rejected,High DTI,Policy_V2
3,APP1000003,C129120,2025-08-13,8500.0,24,Organic,715,8200,0,0.0300,0,0,97,Low,Approved,NaN,Policy_V2
4,APP1000004,C112038,2025-07-02,8500.0,36,Direct,649,11500,2145,0.0300,2,0,62,Medium,Approved,NaN,Policy_V2

In [41]:
app['application_id'].nunique()

120250

In [42]:
app.duplicated().value_counts()

False    120250
Name: count, dtype: int64

In [43]:
app.isna().sum()

application_id                       0
customer_id                          0
application_date                     0
requested_amount                     0
requested_term_months                0
application_channel                  0
credit_score                         0
monthly_income_at_application        0
existing_debt                        0
dti                                601
previous_late_payments               0
previous_defaults                    0
risk_score                           0
risk_band                            0
application_status                   0
rejection_reason                 82272
underwriting_policy_version          0
dtype: int64

### Checking if nulls of rejection_reason is associated with non-rejected application_status

In [44]:
app[(app['application_status']=='Approved') & (app['rejection_reason'].isnull())]

,application_id,customer_id,application_date,requested_amount,requested_term_months,application_channel,credit_score,monthly_income_at_application,existing_debt,dti,previous_late_payments,previous_defaults,risk_score,risk_band,application_status,rejection_reason,underwriting_policy_version
1,APP1000001,C118372,2025-01-25,4500.0,12,Referral,605,6700,2727,0.0395,1,0,86,Low,Approved,NaN,Policy_V1
3,APP1000003,C129120,2025-08-13,8500.0,24,Organic,715,8200,0,0.0300,0,0,97,Low,Approved,NaN,Policy_V2
4,APP1000004,C112038,2025-07-02,8500.0,36,Direct,649,11500,2145,0.0300,2,0,62,Medium,Approved,NaN,Policy_V2
6,APP1000006,C101312,2025-11-20,8000.0,12,Affiliate,718,11800,12730,0.0956,0,0,84,Low,Approved,NaN,Policy_V2
7,APP1000007,C113241,2025-08-14,10000.0,24,Affiliate,717,7900,3169,0.0387,0,0,89,Low,Approved,NaN,Policy_V2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120244,APPDUP100244,C130422,2025-04-27,8500.0,12,Paid Search,816,5700,5354,0.0907,2,0,72,Medium,Approved,NaN,Policy_V2
120245,APPDUP100245,C118369,2025-07-05,39000.0,24,Partner,675,13900,8058,0.0600,0,0,62,Medium,Approved,NaN,Policy_V2
120246,APPDUP100246,C112309,2025-10-21,8500.0,24,Partner,685,8100,2910,0.0343,0,0,100,Low,Approved,NaN,Policy_V2
120247,APPDUP100247,C105090,2025-10-13,4000.0,18,Organic,708,5000,3663,0.0655,0,0,80,Low,Approved,NaN,Policy_V2
120249,APPDUP100249,C133422,2025-12-31,7000.0,24,Referral,692,7500,8025,0.0931,0,0,80,Low,Approved,NaN,Policy_V2

In [45]:
app[app['rejection_reason'].isna()]['application_status'].value_counts()

application_status
Approved     77192
Withdrawn     5080
Name: count, dtype: int64

In [46]:
app = pd.merge(app,loans[['application_id','loan_id']],how = 'left',on = 'application_id')

In [47]:
# Checking unique values in categorical columns
app.columns

Index(['application_id', 'customer_id', 'application_date', 'requested_amount',
       'requested_term_months', 'application_channel', 'credit_score',
       'monthly_income_at_application', 'existing_debt', 'dti',
       'previous_late_payments', 'previous_defaults', 'risk_score',
       'risk_band', 'application_status', 'rejection_reason',
       'underwriting_policy_version', 'loan_id'],
      dtype='str')

In [48]:
app.head()

,application_id,customer_id,application_date,requested_amount,requested_term_months,application_channel,credit_score,monthly_income_at_application,existing_debt,dti,previous_late_payments,previous_defaults,risk_score,risk_band,application_status,rejection_reason,underwriting_policy_version,loan_id
0,APP1000000,C110393,2024-12-03,7000.0,12,Affiliate,592,9700,17055,0.1525,3,0,48,High,Rejected,Policy Criteria,Policy_V1,NaN
1,APP1000001,C118372,2025-01-25,4500.0,12,Referral,605,6700,2727,0.0395,1,0,86,Low,Approved,NaN,Policy_V1,L2000000
2,APP1000002,C103907,2025-12-23,3000.0,12,Social Media,575,1900,1612,0.0839,1,0,37,Very High,Rejected,High DTI,Policy_V2,NaN
3,APP1000003,C129120,2025-08-13,8500.0,24,Organic,715,8200,0,0.0300,0,0,97,Low,Approved,NaN,Policy_V2,L2000001
4,APP1000004,C112038,2025-07-02,8500.0,36,Direct,649,11500,2145,0.0300,2,0,62,Medium,Approved,NaN,Policy_V2,L2000002

In [49]:
# Checking formatting of categorical columns
cols = ['risk_band','application_status','rejection_reason','underwriting_policy_version']
for col in cols:
    print(f'Unique values in {col}: {app[col].unique()}')
    print("="*50)

Unique values in risk_band: <StringArray>
['High', 'Low', 'Very High', 'Medium']
Length: 4, dtype: str
==================================================
Unique values in application_status: <StringArray>
['Rejected', 'Approved', 'Withdrawn']
Length: 3, dtype: str
==================================================
Unique values in rejection_reason: <StringArray>
[    'Policy Criteria',                   nan,            'High DTI',
    'Low Credit Score',  'High Existing Debt', 'Insufficient Income']
Length: 6, dtype: str
==================================================
Unique values in underwriting_policy_version: <StringArray>
['Policy_V1', 'Policy_V2']
Length: 2, dtype: str
==================================================

## Checking collections and repayments table

In [50]:
repayments.head()

,repayment_id,loan_id,customer_id,due_date,payment_date,scheduled_payment,actual_payment,days_past_due,payment_status,missed_payment_flag,partial_payment_flag
0,R4000000,L2000000,C118372,2025-02-26,2025-02-27,353.34,352.13,1,On Time,0,0
1,R4000001,L2000000,C118372,2025-03-28,2025-03-29,353.34,359.53,1,On Time,0,0
2,R4000002,L2000000,C118372,2025-04-27,2025-04-28,353.34,360.36,1,On Time,0,0
3,R4000003,L2000000,C118372,2025-05-27,2025-06-17,353.34,233.12,21,Late,0,1
4,R4000004,L2000000,C118372,2025-06-26,2025-06-28,353.34,359.32,2,On Time,0,0

In [51]:
repayments['missed_payment_flag'].value_counts()

missed_payment_flag
0    483777
1      5661
Name: count, dtype: int64

In [52]:
repayments.info()

<class 'pandas.DataFrame'>
RangeIndex: 489438 entries, 0 to 489437
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   repayment_id          489438 non-null  str
 1   loan_id               489438 non-null  str
 2   customer_id           489438 non-null  str
 3   due_date              489438 non-null  str
 4   payment_date          489438 non-null  str
 5   scheduled_payment     489438 non-null  float64
 6   actual_payment        489438 non-null  float64
 7   days_past_due         489438 non-null  int64
 8   payment_status        489438 non-null  str
 9   missed_payment_flag   489438 non-null  int64
 10  partial_payment_flag  489438 non-null  int64
dtypes: float64(2), int64(3), str(6)
memory usage: 41.1 MB

In [53]:
repayments['due_date'] = pd.to_datetime(repayments['due_date'])
repayments['payment_date'] = pd.to_datetime(repayments['payment_date'])

In [54]:
repayments.duplicated().value_counts()

False    489438
Name: count, dtype: int64

In [55]:
repayments['repayment_id'].nunique()

489438

In [56]:
repayments['payment_status'].unique()

<StringArray>
['On Time', 'Late', 'Partial', 'Missed']
Length: 4, dtype: str

In [57]:
repayments[repayments['payment_status']=='Partial'].head()

,repayment_id,loan_id,customer_id,due_date,payment_date,scheduled_payment,actual_payment,days_past_due,payment_status,missed_payment_flag,partial_payment_flag
30,R4000030,L2000006,C121705,2025-07-15,2025-07-22,1872.87,1422.50,7,Partial,0,1
176,R4000176,L2000030,C121316,2025-11-21,2025-11-25,610.80,462.94,4,Partial,0,1
271,R4000271,L2000047,C124931,2025-12-30,2026-01-01,614.96,488.50,2,Partial,0,1
397,R4000397,L2000072,C113178,2024-12-30,2025-01-10,390.25,345.59,11,Partial,0,1
516,R4000516,L2000091,C101308,2025-10-22,2025-10-31,411.33,298.17,9,Partial,0,1

In [58]:
collections.head()

,collection_id,loan_id,customer_id,collection_date,days_past_due,collection_stage,contact_attempts,amount_recovered,recovery_cost,recovery_status
0,CL5000000,L2000000,C118372,2025-04-21,0,Early,1,0.0,8.71,Contacted
1,CL5000001,L2000000,C118372,2025-05-21,30,30+ DPD,5,0.0,42.25,Contacted
2,CL5000002,L2000000,C118372,2025-06-20,60,60+ DPD,1,0.0,9.57,Contacted
3,CL5000003,L2000000,C118372,2025-07-20,90,90+ DPD,0,0.0,0.00,No Contact
4,CL5000004,L2000000,C118372,2025-08-19,120,Default,2,0.0,23.92,In Progress

In [59]:
collections['collection_id'].nunique()

17262

In [60]:
collections.info()

<class 'pandas.DataFrame'>
RangeIndex: 17262 entries, 0 to 17261
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   collection_id     17262 non-null  str
 1   loan_id           17262 non-null  str
 2   customer_id       17262 non-null  str
 3   collection_date   17262 non-null  str
 4   days_past_due     17262 non-null  int64
 5   collection_stage  17262 non-null  str
 6   contact_attempts  17262 non-null  int64
 7   amount_recovered  17262 non-null  float64
 8   recovery_cost     17262 non-null  float64
 9   recovery_status   17262 non-null  str
dtypes: float64(2), int64(2), str(6)
memory usage: 1.3 MB

In [61]:
collections['collection_date'] = pd.to_datetime(collections['collection_date'])

In [62]:
collections.duplicated().sum()

np.int64(0)

In [63]:
collections['collection_stage'].unique()

<StringArray>
['Early', '30+ DPD', '60+ DPD', '90+ DPD', 'Default', 'Recovery']
Length: 6, dtype: str

In [64]:
collections['recovery_status'].unique()

<StringArray>
['Contacted', 'No Contact', 'In Progress', 'Recovered']
Length: 4, dtype: str

In [65]:
acq.head()

,acquisition_id,customer_id,acquisition_date,acquisition_channel,campaign,partner,acquisition_cost,first_application_date,converted_to_loan
0,AQ100000,C100000,2024-03-06,Direct,Direct_Web,NaN,9.72,2024-04-28,True
1,AQ100001,C100001,2025-07-19,Social Media,Social_Prospecting,NaN,78.86,2025-12-27,True
2,AQ100002,C100002,2025-04-23,Social Media,Social_Retargeting,NaN,103.78,2025-04-28,True
3,AQ100003,C100003,2024-11-16,Paid Search,Search_Brand,NaN,99.80,2024-11-20,True
4,AQ100004,C100004,2024-11-12,Organic,SEO_Organic,NaN,14.00,2025-11-28,True

## Checking the default rate

In [66]:
# Bringing credit score, risk band, loan id, probability of default to collections table
collections = pd.merge(collections, credit_risk[['loan_id','credit_score','risk_band','previous_late_payments','probability_of_default']], how = 'left', on = 'loan_id')

In [67]:
collections['year'] = collections['collection_date'].dt.year

In [68]:
# Checking the total number of default in year 2025
loans['year'] = loans['disbursement_date'].dt.year

In [69]:
loans.groupby('year').agg({
    'loan_id':'count'
    })

      loan_id
year
2024    17708
2025    59322

In [70]:
loans[loans['loan_status']=="Defaulted"].groupby('year')['loan_id'].count()

year
2024     767
2025    2222
Name: loan_id, dtype: int64

## Checking the change in number of total loans and defaulted loans in each year

In [71]:
total_loans = pd.pivot_table(loans, index = None, columns = 'year', values = 'loan_id' , aggfunc = 'count' )
defaulted_loans = pd.pivot_table(loans[loans['loan_status']=='Defaulted'], index = None, columns = 'year', values = 'loan_id', aggfunc = 'count')
total_loans.head()
defaulted_loans.head()
yoy_default = pd.concat([total_loans, defaulted_loans], axis = 0)
yoy_default.columns = ['2024','2025']
yoy_default.index = ['total_loans','default_loans']
yoy_default['perc_change'] = ((yoy_default['2025']/yoy_default['2024'] -1) * 100).round(3)
yoy_default

                2024   2025  perc_change
total_loans    17708  59322      235.001
default_loans    767   2222      189.700

In [72]:
# Checking the number of default loans under each risk band for both years alongwith their avg probability of default and avg number of previous late payments
collections[collections['collection_stage']=='Default'].groupby(['risk_band','year']).agg(
    {'collection_id':'count','probability_of_default':'mean','previous_late_payments':'mean'}).sort_values(
        by = ['year','risk_band'], key = lambda x: x.map({'Low':1,'Medium':2, 'High':3,'Very High': 4}))

                collection_id  probability_of_default  previous_late_payments
risk_band year
Low       2024            102                0.072479                0.323529
          2025           1255                0.082175                0.339442
Medium    2024             47                0.099362                1.127660
          2025            590                0.097967                0.966102
High      2024             26                0.114908                1.653846
          2025            271                0.123170                1.564576
Very High 2024             11                0.135700                3.090909
          2025             82                0.150938                2.500000

### There seems some problem with risk band as low risk band has more number of defaults. Lets dig credit_risk table a little further

In [73]:
credit_risk.groupby('risk_band').agg(
    avg_credit_score = ('credit_score','mean'),
    avg_risk_score = ('risk_score','mean'),
    avg_dti = ('debt_to_income','mean'),
    avg_lti = ('loan_to_income','mean'),
    avg_prob_of_default = ('probability_of_default','mean'),
    avg_late_payments = ('previous_late_payments','mean')
).sort_values(by = 'risk_band', key = lambda x : x.map({'Low':1,'Medium':2,'High': 3,'Very High': 4}))

,avg_credit_score,avg_risk_score,avg_dti,avg_lti,avg_prob_of_default,avg_late_payments
risk_band,,,,,,
Low,722.967553,88.168882,0.067175,0.973557,0.054407,0.263749
Medium,670.898013,68.050858,0.078728,1.148095,0.073477,0.757310
High,630.354044,53.595813,0.084680,1.268870,0.099560,1.433733
Very High,590.464986,36.615546,0.088010,1.322628,0.138827,2.482493

### 1. Column 'risk_score' does not seem consistent with other columns
### 2. Column 'risk_band' seem consistent with other columns as high credit score, low prob_of_default is associated with low risk band

In [74]:
# Dropping the risk

In [75]:
# Checking for a particular loan which is defaulted and has low risk band
loans[loans['loan_id']=='L2000156']

,loan_id,application_id,customer_id,disbursement_date,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,acquisition_channel,underwriting_policy_version,maturity_date,loan_status,year
156,L2000156,APP1000239,C110285,2025-02-03,18000,12,0.0958,1578.97,Consumer,Social Media,Policy_V1,2026-01-29,Defaulted,2025

In [76]:
collections[collections['loan_id']=='L2000156']

,collection_id,loan_id,customer_id,collection_date,days_past_due,collection_stage,contact_attempts,amount_recovered,recovery_cost,recovery_status,credit_score,risk_band,previous_late_payments,probability_of_default,year
13,CL5000013,L2000156,C110285,2025-04-24,0,Early,3,0.0,20.01,Contacted,671,Low,0,0.1,2025
14,CL5000014,L2000156,C110285,2025-05-24,30,30+ DPD,0,0.0,0.00,No Contact,671,Low,0,0.1,2025
15,CL5000015,L2000156,C110285,2025-06-23,60,60+ DPD,1,0.0,4.08,Contacted,671,Low,0,0.1,2025
16,CL5000016,L2000156,C110285,2025-07-23,90,90+ DPD,1,0.0,9.34,Contacted,671,Low,0,0.1,2025
17,CL5000017,L2000156,C110285,2025-08-22,120,Default,3,0.0,19.96,In Progress,671,Low,0,0.1,2025
18,CL5000018,L2000156,C110285,2025-12-31,120,Recovery,4,6011.3,40.47,Recovered,671,Low,0,0.1,2025

In [77]:
collections[collections['loan_id']=='L2000000']

,collection_id,loan_id,customer_id,collection_date,days_past_due,collection_stage,contact_attempts,amount_recovered,recovery_cost,recovery_status,credit_score,risk_band,previous_late_payments,probability_of_default,year
0,CL5000000,L2000000,C118372,2025-04-21,0,Early,1,0.0,8.71,Contacted,605,Low,1,0.0229,2025
1,CL5000001,L2000000,C118372,2025-05-21,30,30+ DPD,5,0.0,42.25,Contacted,605,Low,1,0.0229,2025
2,CL5000002,L2000000,C118372,2025-06-20,60,60+ DPD,1,0.0,9.57,Contacted,605,Low,1,0.0229,2025
3,CL5000003,L2000000,C118372,2025-07-20,90,90+ DPD,0,0.0,0.00,No Contact,605,Low,1,0.0229,2025
4,CL5000004,L2000000,C118372,2025-08-19,120,Default,2,0.0,23.92,In Progress,605,Low,1,0.0229,2025

In [78]:
collections.shape

(17262, 15)

## Checking the delinquent loans

In [79]:
delinquent_loans = pd.pivot_table(collections[collections['collection_stage'].isin(['30+ DPD','60+ DPD','90+ DPD'])], index = 'collection_stage', columns = 'year', values = 'loan_id',aggfunc = 'nunique')
delinquent_loans.columns = ['2024','2025']
delinquent_loans.index = ['30+ DPD','60+ DPD','90+ DPD']
delinquent_loans['perc_change'] = ((delinquent_loans['2025']/delinquent_loans['2024'] - 1) * 100).round(2)
delinquent_loans

         2024  2025  perc_change
30+ DPD   471  2890       513.59
60+ DPD   356  2640       641.57
90+ DPD   263  2415       818.25

In [80]:
loans['loan_status'].value_counts()

loan_status
Paid            39867
Active          30654
Defaulted        2989
Restructured     2617
Written Off       903
Name: count, dtype: int64

In [81]:
loans.head()

,loan_id,application_id,customer_id,disbursement_date,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,acquisition_channel,underwriting_policy_version,maturity_date,loan_status,year
0,L2000000,APP1000001,C118372,2025-01-27,4000,12,0.1090,353.34,Personal,Referral,Policy_V1,2026-01-22,Defaulted,2025
1,L2000001,APP1000003,C129120,2025-08-14,8500,24,0.0920,389.10,Personal,Organic,Policy_V2,2027-08-04,Active,2025
2,L2000002,APP1000004,C112038,2025-07-07,7500,36,0.1052,243.84,Personal,Direct,Policy_V2,2028-06-21,Active,2025
3,L2000003,APP1000006,C101312,2025-11-20,9000,12,0.0914,787.65,Personal,Affiliate,Policy_V2,2026-11-15,Paid,2025
4,L2000004,APP1000007,C113241,2025-08-21,10000,24,0.0916,457.58,Consumer,Affiliate,Policy_V2,2027-08-11,Paid,2025

In [82]:
# Checking which type of loan is getting more defaulted in 2025 than 2024
loan_type_pivot = loans[loans['loan_status']=='Defaulted'].pivot_table(index = 'loan_type',columns = 'year',values = 'loan_id',aggfunc = 'nunique' )
loan_type_pivot.columns = ['2024','2025']
loan_type_pivot['perc_change'] = ((loan_type_pivot['2025']/loan_type_pivot['2024'] - 1)* 100).round(2)
loan_type_pivot

           2024  2025  perc_change
loan_type
Consumer    103   325       215.53
Education    34   137       302.94
Emergency    56   171       205.36
Personal    574  1589       176.83

In [83]:
# Checking which type of acquisition channel is getting more defaulted in 2025 than 2024
acq_type_pivot = loans[loans['loan_status']=='Defaulted'].pivot_table(index = 'acquisition_channel',columns = 'year',values = 'loan_id',aggfunc = 'nunique' )
acq_type_pivot.columns = ['2024','2025']
acq_type_pivot['perc_change'] = ((acq_type_pivot['2025']/acq_type_pivot['2024'] - 1)* 100).round(2)
acq_type_pivot

                     2024  2025  perc_change
acquisition_channel
Affiliate             111   293       163.96
Direct                 13    59       353.85
Email                  12    54       350.00
Organic                12    45       275.00
Paid Search           158   515       225.95
Partner               126   317       151.59
Referral               17    54       217.65
Social Media          318   885       178.30

In [84]:
# Checking which type of underwriting policy is getting more defaulted in 2025 than 2024
policy_type_pivot = loans[loans['loan_status']=='Defaulted'].pivot_table(index = 'underwriting_policy_version',columns = 'year',values = 'loan_id',aggfunc = 'nunique' )
policy_type_pivot.columns = ['2024','2025']
policy_type_pivot['perc_change'] = ((policy_type_pivot['2025']/policy_type_pivot['2024'] - 1)* 100).round(2)
policy_type_pivot

                              2024    2025  perc_change
underwriting_policy_version
Policy_V1                    767.0   463.0       -39.63
Policy_V2                      NaN  1759.0          NaN

In [85]:
loans[loans['loan_status']=='Defaulted'].groupby('year')['underwriting_policy_version'].value_counts()

year  underwriting_policy_version
2024  Policy_V1                       767
2025  Policy_V2                      1759
      Policy_V1                       463
Name: count, dtype: int64

In [86]:
loans[loans['loan_status']=='Defaulted']

,loan_id,application_id,customer_id,disbursement_date,approved_amount,loan_term_months,annual_rate,monthly_payment,loan_type,acquisition_channel,underwriting_policy_version,maturity_date,loan_status,year
0,L2000000,APP1000001,C118372,2025-01-27,4000,12,0.1090,353.34,Personal,Referral,Policy_V1,2026-01-22,Defaulted,2025
5,L2000005,APP1000008,C117785,2025-09-04,4500,9,0.0800,516.81,Personal,Paid Search,Policy_V2,2026-06-01,Defaulted,2025
117,L2000117,APP1000184,C106562,2025-07-01,5500,12,0.0760,477.42,Personal,Paid Search,Policy_V2,2026-06-26,Defaulted,2025
156,L2000156,APP1000239,C110285,2025-02-03,18000,12,0.0958,1578.97,Consumer,Social Media,Policy_V1,2026-01-29,Defaulted,2025
158,L2000158,APP1000245,C112339,2025-07-21,36000,36,0.1194,1194.68,Personal,Referral,Policy_V2,2028-07-05,Defaulted,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76870,L2076870,APP1119757,C111776,2025-08-06,35500,12,0.1148,3145.50,Personal,Paid Search,Policy_V2,2026-08-01,Defaulted,2025
76880,L2076880,APP1119775,C101394,2024-12-09,8500,12,0.0622,732.42,Personal,Social Media,Policy_V1,2025-12-04,Defaulted,2024
76917,L2076917,APP1119830,C129733,2024-12-29,49500,12,0.0646,4270.76,Personal,Email,Policy_V1,2025-12-24,Defaulted,2024
76955,L2076955,APP1119878,C102797,2025-07-16,11000,24,0.0748,494.90,Personal,Direct,Policy_V2,2027-07-06,Defaulted,2025
76966,L2076966,APP1119894,C126150,2025-07-06,12000,36,0.0968,385.41,Emergency,Paid Search,Policy_V2,2028-06-20,Defaulted,2025

In [87]:
collections['recovery_status'].value_counts()

recovery_status
Contacted      10196
No Contact      2547
In Progress     2384
Recovered       2135
Name: count, dtype: int64

In [88]:
repayments[repayments['days_past_due']>30]['loan_id'].nunique()

7914

In [ ]:
#uploading the data to SQL server
import urllib.parse
from sqlalchemy import create_engine

# Database settings
host = r"localhost\SQLEXPRESS"
database = "finance_db"

# Build connection string for Windows Authentication
connection_string = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={host};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# ---------------------------------------------------------
# Upload your 3 DataFrames to SQL Server
# ---------------------------------------------------------

#  Upload Tables
customers.to_sql("customers", engine, if_exists="append", index=False)
credit_risk.to_sql("credit_risk", engine, if_exists="append", index=False)
loans.to_sql("loans", engine, if_exists="append", index=False)
collections.to_sql("collections", engine, if_exists="append", index=False)
repayments.to_sql("repayments", engine, if_exists="append", index=False)
acq.to_sql("acquisition", engine, if_exists="append", index=False)
app.to_sql("applications", engine, if_exists="append", index=False)
monthly_kpis.to_sql("monthly_kpis", engine, if_exists="append", index=False)


print("All tables uploaded successfully to 'finance_db'!")

DatabaseError: Execution failed on sql 'INSERT INTO repayments (application_id, customer_id, application_date, requested_amount, requested_term_months, application_channel, credit_score, monthly_income_at_application, existing_debt, dti, previous_late_payments, previous_defaults, risk_score, risk_band, application_status, rejection_reason, underwriting_policy_version, loan_id) VALUES (:application_id, :customer_id, :application_date, :requested_amount, :requested_term_months, :application_channel, :credit_score, :monthly_income_at_application, :existing_debt, :dti, :previous_late_payments, :previous_defaults, :risk_score, :risk_band, :application_status, :rejection_reason, :underwriting_policy_version, :loan_id)': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_date'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'requested_amount'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'requested_term_months'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_channel'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'credit_score'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'monthly_income_at_application'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'existing_debt'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'dti'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'previous_late_payments'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'previous_defaults'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'risk_score'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'risk_band'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_status'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'rejection_reason'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'underwriting_policy_version'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_id'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_date'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'requested_amount'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'requested_term_months'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_channel'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'credit_score'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'monthly_income_at_application'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'existing_debt'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'dti'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'previous_late_payments'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'previous_defaults'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'risk_score'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'risk_band'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'application_status'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'rejection_reason'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'underwriting_policy_version'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: INSERT INTO repayments (application_id, customer_id, application_date, requested_amount, requested_term_months, application_channel, credit_score, monthly_income_at_application, existing_debt, dti, previous_late_payments, previous_defaults, risk_scor ... 6491 characters truncated ... ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('APP1000000', 'C110393', datetime.datetime(2024, 12, 3, 0, 0), 7000.0, 12, 'Affiliate', 592, 9700, 17055, 0.1525, 3, 0, 48, 'High', 'Rejected', 'Policy Criteria', 'Policy_V1', None, 'APP1000001', 'C118372', datetime.datetime(2025, 1, 25, 0, 0), 4500.0, 12, 'Referral', 605, 6700, 2727, 0.0395, 1, 0, 86, 'Low', 'Approved', None, 'Policy_V1', 'L2000000', 'APP1000002', 'C103907', datetime.datetime(2025, 12, 23, 0, 0), 3000.0, 12, 'Social Media', 575, 1900, 1612, 0.0839, 1, 0, 37, 'Very High' ... 1988 parameters truncated ... 6, 'Paid Search', 637, 11500, 5660, 0.0809, 1, 0, 65, 'Medium', 'Withdrawn', None, 'Policy_V2', None, 'APP1000114', 'C114168', datetime.datetime(2025, 11, 28, 0, 0), 7500.0, 18, 'Paid Search', 574, 9100, 6903, 0.0678, 1, 0, 58, 'High', 'Approved', None, 'Policy_V2', 'L2000078', 'APP1000115', 'C126610', datetime.datetime(2025, 5, 16, 0, 0), 19500.0, 9, 'Social Media', 713, 15700, 0, 0.03, 0, 0, 81, 'Low', 'Approved', None, 'Policy_V2', 'L2000079')]
(Background on this error at: https://sqlalche.me/e/21/f405)

In [100]:
#uploading the data to SQL server
import urllib.parse
from sqlalchemy import create_engine

# Database settings
host = r"localhost\SQLEXPRESS"
database = "finance_db"

# Build connection string for Windows Authentication
connection_string = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={host};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

acq.to_sql("acq", engine, if_exists="replace", index=False)
app.to_sql("applications", engine, if_exists="replace", index=False)
monthly_kpis.to_sql("monthly_kpis", engine, if_exists="replace", index=False)

24

In [101]:
#uploading the data to SQL server
import urllib.parse
from sqlalchemy import create_engine

# Database settings
host = r"localhost\SQLEXPRESS"
database = "finance_db"

# Build connection string for Windows Authentication
connection_string = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={host};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

app.to_sql("app", engine, if_exists="replace", index=False)
repayments.to_sql("repayments", engine, if_exists="replace", index=False)

188